In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

### a)
### $$A \cdot B = \varnothing$$
### $$B \cdot A = \varnothing$$
### б)
### $$A \cdot B = \varnothing$$
#### $B \cdot A $ Размерность равна 3 x 2
### в)
#### $A \cdot B $ Размерность равна 3 x 3
#### $B \cdot A $ Размерность равна 8 x 8
### г)
#### $A \cdot B $ Размерность равна 4 x 4
#### $B \cdot A $ Размерность равна 4 x 4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix}.$

$$A\cdot B=\begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5 \\
3 \cdot 4 + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5 \\
\end{pmatrix} =
\begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}. $$

$$B\cdot A=\begin{pmatrix}
4 \cdot 1 + (-1) \cdot 3 & 4 \cdot (-2) + (-1) \cdot 0 \\
0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 0 \\
\end{pmatrix} =
\begin{pmatrix}
1 & -8\\
15 & 0
\end{pmatrix}. $$

In [2]:
A = np.array([[1, -2],[3, 0]])
B = np.array([[4, -1],[0, 5]])

print(f'Матрица A + B\n{A + B}')
print(f'Матрица AB\n{A @ B}')
print(f'Матрица BA\n{B @ A}')

Матрица A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}.$

In [3]:
A = np.array([[1, 7],[3, -6]])
B = np.array([[0, 5],[2, -1]])
C = np.array([[2, -4],[1, 1]])

print(f'Линейная комбинация \n{A * 3 + B * (-2) + 4 * C}')

Линейная комбинация 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [4]:
A = np.array([[4, 1],[5, -2],[2, -3]])

print(f'Матрица A * At\n{A @ A.T}')
print(f'Матрица At * A\n{A.T @ A}')

Матрица A * At
[[17 18  5]
 [18 29 16]
 [ 5 16 13]]
Матрица At * A
[[ 45 -12]
 [-12  14]]


#### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\
cosx & sinx
\end{vmatrix};$$

б)

$$\begin{vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end{vmatrix};
$$

   в)

$$\begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{vmatrix}.$$

### a) $$ \sin{x} \cdot \sin{x} - (\cos{x} \cdot (-\cos{x})) = 1$$
### б)

$$\begin{vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end{vmatrix}=
4\cdot\begin{vmatrix}
5 & 1\\
0 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
0 & 3\\
0 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
0 & 5\\
0 & 0
\end{vmatrix}=4\cdot(5\cdot9)-2\cdot(0)+3\cdot(0)= 180
$$

In [5]:
A = np.array([[4, 2, 3],[0, 5, 1],[0, 0, 9]])

print(f'Определитель:\n{np.linalg.det(A):.0f}')

Определитель:
180


#### в)
$$\begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{vmatrix}=
1\cdot\begin{vmatrix}
5 & 6\\
8 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
4 & 6\\
7 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
4 & 5\\
7 & 8
\end{vmatrix}= -3 + 12 - 9 = 0
$$

In [6]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(f'Определитель:\n{np.linalg.det(A):.0f}')

Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = 16$;

   б) $det(A^{T}) = 4$;

   в) $det(2A) = 8$.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
\end{pmatrix}$$

вырожденная.

In [7]:
A = np.array([[-2, 7, -3],[4, -14, 6],[-3, 7, 13]])

print(f'Определитель:\n{np.linalg.det(A):.0f}')
print('Вывод: матрица вырожденная')

Определитель:
0
Вывод: матрица вырожденная


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3\\
2 & 3 & 5 & 6
\end{pmatrix}.$

In [8]:
A = np.array([[1, 2, 3],[1, 1, 1],[2, 3, 4]]) # 3 строка сумма 1 и 2 строки
r = np.linalg.matrix_rank(A)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [9]:
A = np.array([[0, 0, 2, 1],[0, 0, 2, 2],[0, 0, 4, 3],[2, 3, 5, 6]]) # 3 строка сумма 1 и 2 строки
r = np.linalg.matrix_rank(A)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
