1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\
0 & 0 & 5\\
3 & -4 & 2\\
1 & 6 & 5\\
0 & 1 & 0
\end{pmatrix}.$$

In [28]:
import numpy as np

A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

U, s, W = np.linalg.svd(A)

V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [29]:
print(f'S:{s}\n V:{V}\n D:{D}')

S:[8.82486885 6.14060608 2.53271528]
 V:[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]
 D:[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;

    б) норму Фробениуса.

In [30]:
#a
D[0,0], np.linalg.norm(A, 2)

(8.824868854820444, 8.824868854820444)

In [31]:
#б
np.linalg.norm(A, 'fro')

11.045361017187261